version: '3'
services:
  weatherappenv:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/opt/apps
    ports:
      - "8080:8080"
      - "3000:3000"
    environment:
      WEATHER_APP_ID: ${WEATHER_APP_ID}
